### ISSUE TITLE
运行python try_chat.py出现导包失败，可这个包已经按照要求安装了

### ISSUE THREAD

**Issue by MemoryOldTime** [Chen-Yang-Liu/Change-Agent#3]
(agent) F:\Project\Change-Agent\Multi_change>python try_chat.py
Traceback (most recent call last):
  File "F:\Project\Change-Agent\Multi_change\try_chat.py", line 2, in <module>
    from lagent.actions import ActionExecutor, GoogleSearch, PythonInterpreter, Visual_Change_Process_PythonInterpreter
ImportError: cannot import name 'Visual_Change_Process_PythonInterpreter' from 'lagent.actions' (C:\Users\XD\.conda\envs\agent\lib\site-packages\lagent\actions\__init__.py)

**Comment by Chen-Yang-Liu** [comment]
> (agent) F:\Project\Change-Agent\Multi_change>python try_chat.py Traceback (most recent call last): File "F:\Project\Change-Agent\Multi_change\try_chat.py", line 2, in from lagent.actions import ActionExecutor, GoogleSearch, PythonInterpreter, Visual_Change_Process_PythonInterpreter ImportError: cannot import name 'Visual_Change_Process_PythonInterpreter' from 'lagent.actions' (C:\Users\XD.conda\envs\agent\lib\site-packages\lagent\actions__init__.py)

按理说不会有这个问题，请问目前是否已经解决了呢？
